### ISSUE TITLE
Smart separation character option

### ISSUE THREAD

**Issue by novoid** [DerBeutlin/date2name.el#1]
Hi, thanks for this great tool!

I'd love to have the smart date/time-stamp to file name separation character as date2name here as well:

If the original file name contains at least one space character, a space character is used as separation character: `2018-07-08 original file.txt`

If no space is found in the original file name, an underscore is used as a separator character: `2018-07-08_original_file.txt`

I understand that not everybody is happy with such a semi-smart algorithm. So you might probably add a toggle option for this behavior.

**Comment by DerBeutlin** [comment]
Thanks for the proposal, you can try out the PR #2 and if it suits yourn needs I will merge it.

**Comment by novoid** [comment]
Maybe I did something wrong here but https://raw.githubusercontent.com/DerBeutlin/date2name.el/dbc527d6ae366360da418595969186f17b4e80f6/date2name.el does always use underscore as separation character.

How I tested:
`touch "foo bar baz.txt" "foo bar.txt" "foo_bar.txt"` in my shell and the either mark all and invoke `date2name-dired-add-date-to-name` or apply it to single files.

**Comment by DerBeutlin** [comment]
Did you enabled the feature through `(setq date2name-enable-smart-separation-character-chooser t)` ?   Because your example works for me.

**Comment by novoid** [comment]
Of course not - stupid me. Sorry. I should have known that you follow your great habit of enabling those things via a variable.

However, I do have an issue since `file-attribute-modification-time` was only introduced with Emacs 26 http://ergoemacs.org/emacs/emacs26_features.html and, at home, my Debian stable features Emacs 25.1.1.

Do you, by chance, have a backward-compatible alternative? (I run Emacs 26 on Win10, Emacs 25 on Debian, and Emacs 27 snapshot on a Debian notebook.)

**Comment by DerBeutlin** [comment]
As far as I can tell only the function `file-attribute-modification-time` was added to emacs 26 but the `file-attributes` function was already there?
Then one could just define the function as
```
(defun file-attribute-modification-time (attributes)
  "extracts the modification time from ATTRIBUTES"
  (nth 5 attributes))
```

**Comment by novoid** [comment]
Perfect.

With the defun it works like charm. Even with multiple different files selected that require different separation characters.
