### ISSUE TITLE
if: Symbol’s function definition is void: file-attribute-modification-time

### ISSUE THREAD

**Issue by montaropdf** [DerBeutlin/date2name.el#3]
Hi,

When calling either `date2name-dired-add-date-to-name` or `date2name-dired-add-datetime-to-name` I get the error message in the title.

I have tried with a file at point and one or more marked files with the same result.

It looks like the call `(file-attributes filename)`, in function `date2name-add-date-to-name`, didn't return any information, if I understand the error correctly.

System information:
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-11, modified by Debian
Org mode version 9.1.14 (9.1.14-3-geb9955a-elpaplus @ /home/roland/.emacs.d/elpa/org-plus-contrib-20180924/)
OS: PureOS (Debian Linux derivative)

Regards,

Roland.

**Comment by DerBeutlin** [comment]
The problem is that the function  ` file-attribute-modification-time` is not defined in emacs prior to Emacs 26.1.

I pushed a fix which should define the function if it is not yet defined. Would be nice if you could check it out and close the issue if everything works.

**Comment by montaropdf** [comment]
Hi,

Just tested the new commit.

Now it works as it should be.

Thank you.
